import type { PersonaConfig, PersonaId } from '../shared/types/persona';

export const PERSONAS: Record<PersonaId, PersonaConfig> = {
  dealer_broker: {
    id: 'dealer_broker',
    label: 'Dealer / Broker',
    icon: 'handshake',
    coreMission: 'Identify ownership, assess market position, initiate acquisition or sale conversations',
    primaryContacts: ['Owner', 'Operator', 'Manager', 'CFO', 'Controller'],
    secondaryContacts: ['Chief Pilot', 'Director of Aviation', 'DOM'],
    dataPriorities: ['relationships', 'transactionsIntel', 'marketIntel', 'flightIntel'],
    reportTone: 'Concise, direct, deal-oriented. No fluff.',
    outreachEnabled: true,
    dashboardWidgets: [
      'aircraft_profile', 'ownership_chain', 'market_position',
      'comparable_sales', 'top_contacts', 'outreach_actions', 'contact_pack',
    ],
  },
  fbo: {
    id: 'fbo',
    label: 'FBO',
    icon: 'building-2',
    coreMission: 'Understand aircraft types and the people associated with them to capture transient and based traffic',
    primaryContacts: ['Chief Pilot', 'Scheduler', 'Dispatch', 'DOM'],
    secondaryContacts: ['Owner', 'Operator', 'Manager', 'Executive Assistant'],
    dataPriorities: ['aircraft_type', 'flightIntel', 'relationships', 'contacts'],
    reportTone: 'Operational, hospitality-aware. Focus on aircraft needs and people.',
    outreachEnabled: true,
    dashboardWidgets: [
      'aircraft_profile_fbo', 'flight_pattern_map', 'visit_frequency',
      'crew_contacts', 'passenger_pathway', 'service_opportunity_notes',
    ],
  },
  mro: {
    id: 'mro',
    label: 'MRO',
    icon: 'wrench',
    coreMission: 'Assess maintenance opportunity based on aircraft age, type, utilization, and decision-maker access',
    primaryContacts: ['DOM', 'Chief Pilot', 'Director of Maintenance', 'Director of Aviation'],
    secondaryContacts: ['Operator', 'Manager', 'Scheduler'],
    dataPriorities: ['aircraft_profile', 'flightIntel', 'relationships', 'transactionsIntel'],
    reportTone: 'Technical, practical. Reference model-specific maintenance considerations.',
    outreachEnabled: true,
    dashboardWidgets: [
      'aircraft_technical_profile', 'utilization_estimate', 'maintenance_window_signals',
      'operator_fleet_size', 'maintenance_decision_makers', 'outreach_actions',
    ],
  },
  charter: {
    id: 'charter',
    label: 'Charter',
    icon: 'plane',
    coreMission: 'Assess aircraft availability, utilization patterns, and competitive positioning in the charter market',
    primaryContacts: ['Operator', 'Manager', 'Scheduler', 'Dispatch'],
    secondaryContacts: ['Chief Pilot', 'Owner'],
    dataPriorities: ['flightIntel', 'relationships', 'aircraft_profile', 'marketIntel'],
    reportTone: 'Market-aware, operational. Focus on availability and utilization.',
    outreachEnabled: true,
    dashboardWidgets: [
      'aircraft_charter_profile', 'utilization_analysis', 'route_heatmap',
      'dead_leg_indicators', 'operator_identification', 'charter_market_context', 'outreach_actions',
    ],
  },
  fleet_management: {
    id: 'fleet_management',
    label: 'Fleet Management',
    icon: 'layout-grid',
    coreMission: 'Monitor operational health, ownership structure, and utilization across managed or tracked aircraft',
    primaryContacts: ['Owner', 'Operator', 'Manager', 'Chief Pilot', 'DOM'],
    secondaryContacts: ['CFO', 'Controller', 'Scheduler'],
    dataPriorities: ['relationships', 'flightIntel', 'transactionsIntel', 'aircraft_profile', 'marketIntel'],
    reportTone: 'Analytical, operations-focused. Benchmark-oriented.',
    outreachEnabled: false,
    dashboardWidgets: [
      'aircraft_operational_profile', 'ownership_chain_verification', 'utilization_benchmark',
      'flight_pattern_analysis', 'fleet_context_panel', 'operational_alerts', 'asset_valuation_context',
    ],
  },
  finance: {
    id: 'finance',
    label: 'Finance',
    icon: 'landmark',
    coreMission: 'Fleet valuation, KYC due diligence on aircraft ownership, and flight pattern analysis for compliance',
    primaryContacts: ['Owner', 'Manager', 'CFO', 'Controller'],
    secondaryContacts: ['Operator', 'Director of Aviation'],
    dataPriorities: ['transactionsIntel', 'marketIntel', 'relationships', 'flightIntel', 'aircraft_profile'],
    reportTone: 'Analytical, compliance-aware. Flag unknowns explicitly. No speculation.',
    outreachEnabled: false,
    dashboardWidgets: [
      'aircraft_collateral_profile', 'ownership_chain_deep', 'valuation_context',
      'transaction_timeline', 'kyc_flight_analysis', 'compliance_flags', 'data_confidence_panel',
    ],
  },
  catering: {
    id: 'catering',
    label: 'Catering',
    icon: 'utensils',
    coreMission: 'Identify inbound aircraft to target airports and connect with the people who arrange provisioning',
    primaryContacts: ['Scheduler', 'Dispatch', 'Executive Assistant', 'Chief Pilot'],
    secondaryContacts: ['Operator', 'Manager'],
    dataPriorities: ['flightIntel', 'aircraft_profile', 'relationships', 'contacts'],
    reportTone: 'Service-oriented, practical. Focus on timing and logistics.',
    outreachEnabled: true,
    dashboardWidgets: [
      'aircraft_cabin_profile', 'arrival_pattern_analysis', 'service_window_estimate',
      'provisioning_contacts', 'outreach_actions',
    ],
  },
  ground_transportation: {
    id: 'ground_transportation',
    label: 'Ground Transportation',
    icon: 'car',
    coreMission: 'Identify where aircraft land, when they arrive, and who needs ground transport',
    primaryContacts: ['Executive Assistant', 'Scheduler', 'Manager'],
    secondaryContacts: ['Operator', 'Chief Pilot', 'Dispatch'],
    dataPriorities: ['flightIntel', 'relationships', 'contacts', 'aircraft_profile'],
    reportTone: 'Service-oriented, logistics-focused. Lead with where and when.',
    outreachEnabled: true,
    dashboardWidgets: [
      'destination_analysis', 'arrival_timing_patterns', 'passenger_pathway_contacts',
      'aircraft_category_context', 'outreach_actions',
    ],
  },
  detailing: {
    id: 'detailing',
    label: 'Detailing',
    icon: 'sparkles',
    coreMission: 'Identify where aircraft are based, how often they fly, and who schedules ground services',
    primaryContacts: ['Scheduler', 'DOM', 'Chief Pilot', 'Dispatch'],
    secondaryContacts: ['Operator', 'Manager'],
    dataPriorities: ['flightIntel', 'aircraft_profile', 'relationships', 'contacts'],
    reportTone: 'Practical, service-oriented. Focus on location, frequency, and access.',
    outreachEnabled: true,
    dashboardWidgets: [
      'aircraft_size_profile', 'home_base_analysis', 'flight_frequency',
      'service_scheduling_contacts', 'outreach_actions',
    ],
  },
};

export const PERSONA_LIST: PersonaConfig[] = Object.values(PERSONAS);
